// <auto-generated />
using System;
using Habble.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Habble.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220817133916_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Habble.Models.Application", b =>
                {
                    b.Property<int>("ApplicaitonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicaitonId"), 1L, 1);

                    b.Property<bool>("AcceptedPrivacy")
                        .HasColumnType("bit");

                    b.Property<int>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TypeOfProject")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ApplicaitonId");

                    b.ToTable("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
